### ISSUE TITLE
Using custom fields added via Settings Template resets the Templates paths on a Report

### ISSUE THREAD

**Issue by adrianbunea** [barrelstrength/craft-sprout-reports#115]
### Description
I have added two Date fields to my Report, after saving the paths for the first time, the two new fields appear, after filling in any of those fields and save, I am returned to the first field, where I need to input the Template paths, and the two custom fields are gone.

Paths are setup like this:
![image](https://user-images.githubusercontent.com/42218790/138892563-958001e8-eb2d-4eac-8dfa-a7c3e9dfa485.png)

Files are setup like this:
![image](https://user-images.githubusercontent.com/42218790/138892625-12be4ad0-b1d1-480f-8792-0f257d520257.png)

Settings template is setup like this:
```
{% import "_includes/forms" as forms %}

{{ forms.dateField({
  label: "Start Date"|t,
  instructions: "The date when to start looking for payments."|t,
  id: "datetimeStartDate",
  name: "datetimeStartDate",
  value: (settings.datetimeStartDate is defined ? settings.datetimeStartDate : null),
  required: false
}) }}


{{ forms.dateField({
  label: "End Date"|t("plugin-handle"),
  instructions: "The date when to stop looking for payments."|t,
  id: "datetimeEndDate",
  name: "datetimeEndDate",
  value: (settings.datetimeEndDate is defined ? settings.datetimeEndDate : null),
  required: false
}) }}

{%- includejs %}

    $('#settings-datetimeStartDate-field .datewrapper input:first-of-type').datepicker($.extend({
    defaultDate: new Date({{ now.year }}, {{ now.month }}, {{ now.day }})
    }, Craft.datepickerOptions));

    $('#settings-datetimeEndDate-field .datewrapper input:first-of-type').datepicker($.extend({
    defaultDate: new Date({{ now.year }}, {{ now.month }}, {{ now.day }})
    }, Craft.datepickerOptions));

    var $timePickerStartDate = $('#settings-datetimeStartDate-field .timewrapper input:first-of-type');
    var $timePickerEndDate = $('#settings-datetimeEndDate-field .timewrapper input:first-of-type');

    $timePickerStartDate.timepicker($.extend({}, Craft.timepickerOptions));
    $timePickerEndDate.timepicker($.extend({}, Craft.timepickerOptions));

{%- endincludejs %}
```

After saving the report template paths, I get this:
![image](https://user-images.githubusercontent.com/42218790/138893849-e30bd23b-848e-44c0-b31a-3b8c105f5745.png)

After inputting the two dates, and save it, I get returned to the original screen where I need to add the template paths:
![image](https://user-images.githubusercontent.com/42218790/138893998-df517d83-01ca-4a6b-97dc-50441bc26ebd.png)

### Steps to reproduce
1. Create a new Report
2. Setup paths for templates, especially for a settings, and make sure to add a date field
3. Save the Report
4. Edit the Report again
5. Modify the custom date field
6. Save the template again => Get returned to the first view, with the template paths gone and no more fields.

### Additional info

- Craft version: Craft Pro 3.5.8
- PHP version: 7.2.34
- Database driver & version: MySQL 5.7.31
- Plugins & versions:
    Sprout Email | 4.4.8
    Sprout Reports | 1.5.9

**Comment by BenParizek** [comment]
Thanks for the clear description @adrianbunea. I've just released Sprout Reports v1.5.12 which should solve the issue.

It seems Craft must have changed how the Timepicker was loading which was causing a javascript error and disabling those autosuggest template fields during the second submission.
