### ISSUE TITLE
You need to be on at least Sprout Reports 0.9.3 before you can update to Sprout Reports 1.5.12.

### ISSUE THREAD

**Issue by romainpoirier** [barrelstrength/craft-sprout-reports#119]
### Description (screenshots, logs, ...)

I can't install Sprout Reports, neither from the Plugin Store neither from `composer install`. 
I always get this error: `You need to be on at least Sprout Reports 0.9.3 before you can update to Sprout Reports 1.5.12`.
I'm not trying to update from a previous version to another one. The plugin is currently not installed.
The only particularity is that this project is a migration of an old Craft 2 project.

### Additional info

- Craft version: Craft Pro 3.7.34
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.34
- Plugins & versions: 1.5.12

**Comment by BenParizek** [comment]
@romainpoirier I've just tested installing Sprout Reports and haven't had any issues installing it. Perhaps someone installed it briefly on Craft 2 and removed it and some info is hanging around and referencing an older version of the plugin.

Can you check your `craft_plugins` table in the database and see if you have a row that references an old version of Sprout Reports? If so, you can probably just delete that. But you may also want to check if you have any old tables for sprout reports. One to look for would be `craft_sproutreports_reports`.

**Comment by romainpoirier** [comment]
Thank you, deleting reference of the plugin in the `craft_plugins` table fix it.
