### ISSUE TITLE
Twig/HTML not rendered in results

### ISSUE THREAD

**Issue by howells** [barrelstrength/craft-sprout-reports#120]
### Description (screenshots, logs, ...)

HTML in the results twig file doesn't appear to be rendered in results.

### Steps to reproduce

1. Create a results file
2. Include some html as part of the addRow array
3. View report
4. The raw html is output, rather than rendered html

I used one of the example snipped in my code:

```
{% for result in results %}
{% do craft.sproutReports.addRow([
  result.ingredient,
  isExport ? 'Not Link' : '<a href="">Link</a>',
	result.count
]) %}
{% endfor %}
```

But just the raw html is output when viewing the report:

<img width="931" alt="CleanShot 2022-03-28 at 18 13 27@2x" src="https://user-images.githubusercontent.com/145849/160451654-5b901361-e078-4663-9074-79f1350ac7f3.png">

### Additional info

- Craft version: 3.7.37
- PHP version: 8.0.12
- Database driver & version:   MySQL 5.7.34
- Plugins & versions:  Sprout Reports 1.5.12

**Comment by BenParizek** [comment]
Do you have the Allow HTML setting enabled on the report itself?

![Allow HTML](https://user-images.githubusercontent.com/309735/160459483-b8ebf2ac-a459-4ee9-8f5b-a26e06733197.png)

**Comment by howells** [comment]
@BenParizek damn! So sorry, I don't think I've ever noticed that setting 😅
