### ISSUE TITLE
Template not found when trying to create new report

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-reports#2]
I'm unable to create a new report. I believe I'm updated to the latest Sprout Core and Sprout Reports for Craft 3. This happens if I hit "New Report" from the Reports page or from the DataSource page.

After hitting "New Report", I get this template error:
http://share.barrelstrength.co/061Y0Y2q1u2v

The URL that is generated by the `BaseDataSource::getUrl()` method appears to be this:

```
http://craft3.dev/admin/sprout-reports/reports/sproutreports.barrelstrength/sproutreports/integrations/sproutreports/datasources/categories/new
```

**Comment by alexmglover** [comment]
@BenParizek I'm still seeing this issue. What was the resolution here?

**Comment by pdaleramirez** [comment]
Fixed this issue on sprout base repo here https://github.com/barrelstrength/craft-sprout-base/commit/56d0f1a934080b8d3ca4d1fd23ae1dc7442e977b
