### ISSUE TITLE
Installing from scratch results in error after install

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-reports#24]
Unknown Property: Setting unknown property: barrelstrength\sproutbase\records\sproutreports\DataSource::type

http://share.barrelstrength.co/323Y2D042D0L

Missing pluginId column. dataSourceId table never got renamed.

**Comment by pdaleramirez** [comment]
The reason for this is that the old beta version does require sprout-base v3.0.0 in composer.json. When installing sprout-report it needs to have the latest beta version.
