### ISSUE TITLE
[FR] Use `nl2br` to consistently parse line breaks within a cell

### ISSUE THREAD

**Issue by lindseydiloreto** [barrelstrength/craft-sprout-reports#26]
I'm using the Twig template report for the first time… it’s awesome! It’s super cool that you can pump HTML into the table.

But it's impossible to render line breaks within a single cell consistently. If you use `<br/>` it looks great online but terrible as a download. Conversely, if you use `\n` it looks great as a download, but terrible online.

---

**Using `<br/>`**

_online_
<img width="405" alt="2018-06-06 at 4 22 04 pm" src="https://user-images.githubusercontent.com/5309692/41070302-df9e1dce-69a6-11e8-9f20-eb04fb1e0674.png">

_download_
<img width="532" alt="2018-06-06 at 4 30 37 pm" src="https://user-images.githubusercontent.com/5309692/41070317-fa3c2374-69a6-11e8-8259-6380fa205fcf.png">

---

**Using `\n`**

_online_
<img width="430" alt="2018-06-06 at 4 17 51 pm" src="https://user-images.githubusercontent.com/5309692/41070255-a4ddc162-69a6-11e8-9815-04233db0f3ee.png">

_download_
<img width="399" alt="2018-06-06 at 4 18 17 pm" src="https://user-images.githubusercontent.com/5309692/41070280-bfa57c1a-69a6-11e8-84b2-c5a705c66995.png">

---

I'd recommend using the `nl2br` tag when rendering everything online. That way, it will be very easy to render line breaks in both places.

**Comment by lindseydiloreto** [comment]
I just hacked this in the Craft 2 version, it was super easy... Just add the `nl2br` filter to this line:

https://github.com/barrelstrength/craft-sprout-reports/blob/v0/templates/results/index.html#L87

    {{ property|nl2br|raw }}

I took a quick look at the Craft 3 version, and couldn't figure out where to put it. The internal architecture has changed significantly.

**Comment by BenParizek** [comment]
Thanks @lindseydiloreto 

We'll look into adding this formally soon. 

If you are curious, in Craft 3, the templates for most of our plugins are in Sprout Base:
https://github.com/barrelstrength/craft-sprout-base/blob/v2/src/app/reports/templates/results/index.html#L82

This allows us to give users the ability to use reports in other plugins. For example, Sprout Forms includes reporting powered by Sprout Reports without ever needing to install Sprout Reports!
