### ISSUE TITLE
Sample reports produce Twig Runtime Errors

### ISSUE THREAD

**Issue by MischaSz** [barrelstrength/craft-sprout-reports#28]
### Description
Both sample reports (Active User report and Tutorial report) are producing similar errors messages:

Twig_Error_Runtime: Key "datetimeStartDate" for array with keys "limitByDateRange, resultsTemplate, settingsTemplate" does not exist in "__string_template__ab2f195c9907e88d2036c33ea895b05aedadabb25d4e9d3225aaf8e5e8ab88bf" at line 199. in /Users/xxx/MAMP/sites/xxx-www/vendor/twig/twig/lib/Twig/Extension/Core.php:1500

### Steps to reproduce

1. Installed Sprout Reports
2. Copied example reports to template directory
3. Created new report with example settings and example results twig templates
4. Run report

### Additional info

- Craft version: Craft Pro 3.0.18
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions: Sprout Reports 1.0.0-beta.12

**Comment by pdaleramirez** [comment]
There was a problem on the example twig template. I have fixed it on this commits https://github.com/barrelstrength/craft-sprout-reports/commit/aea7f8b32c8481e6bf767a17c42b73370db21ced

https://github.com/barrelstrength/craft-sprout-reports/commit/5299cb327d9c8440e7aa9e7eb6ea60b17e3d67d6

**Comment by BenParizek** [comment]
@MischaSz This issue has been resolved in Sprout Reports v1.0.0-beta.13, now available in the plugin store.
