### ISSUE TITLE
allowHtml setting doesn't behave as expected

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-reports#30]
app/reports/templates/results/index.html honors the HTML setting correctly, but `{{ property | nl2br | raw }}` escapes HTML while `{{ property | raw }}` does not. 

It appears we need to update the order of the Twig filters:
`{{ property | raw | nl2br }}`

**Comment by pdaleramirez** [comment]
This has been updated on develop branch. I remember i was working on this but could not find the commit on the changes
