### ISSUE TITLE
Question: How can I add a category picker to a settings template?

### ISSUE THREAD

**Issue by missmatsuko** [barrelstrength/craft-sprout-reports#35]
I want to create a category picker for a report so the client can generate reports for one or more categories in a given category group.

Initially, I tried to use checkboxes from the categories, but I wasn't able to set the values of the checkboxes to the category IDs. I think it's because the IDs are numerical and they get reindexed somehow.

Now I'm trying to use the `elementSelect` form macro (located at `craft/app/templates/_includes/forms/elementSelect.html`) from Craft for this. I think it's the appropriate one, but not totally sure.

I'm trying to follow the `dateTimeField` from the `craft/plugins/sproutreports/examples/templates/_reports/tutorialreport/options.html`, which is also using a Craft form macro that requires JS to function.

I'm finding it pretty difficult to figure out what kind of values the macro requires. Can someone give me a little guidance, or maybe add it to the example options template?

**Comment by BenParizek** [comment]
@missmatsuko 

I don't have a quick example to share with you. It does take some familiarity or exploration of the Craft macros to understand how to use them and Element Relations field may require additional javascript and a deeper understanding of how to interact with the data.

It looks like you did already find the Craft templates folder to explore. Perhaps search the whole app folder for `forms.elementSelect` to see if you can find any examples of how the macro is used. It's quite possible you may need to hard code or dynamically set some values to get the macro working as you need it to.

Checkboxes or a more simple field type will definitely be the easier approach. If you are looking to better understand how to format the data, I did pull together a list of example inputs for most of the common fields here:
https://straightupcraft.com/articles/craft-cms-field-guide-twig?view=input

If you want to post a more specific example of what you are trying to use for checkboxes, I could comment further.

**Comment by missmatsuko** [comment]
Thanks for the response!

I might give the elementSelect field another attempt, but I wasn't making much progress with it. 

The problem with my checkboxes is that I can't seem to set its value to the category's IDs. I think it's because they're numbers, so the array gets reindexed.

So now I'm using category slugs for the input values instead. I'm pretty sure that means I'll have to add an extra step later to convert the selected slugs back into IDs to use in a relation query.

Here's my checkboxes code:
```
{% set customerTypesCategories = craft.categories.group('shopUserType') %}
{% set customerTypesOptions = {} %}

{% for category in customerTypesCategories %}
	{% set customerTypesOptions = customerTypesOptions|merge({(category.slug): category.title}) %}
{% endfor %}

{{ forms.checkboxSelectField({
	label: 'Customer Types'|t,
	name: 'options[customerTypes]',
	options: customerTypesOptions,
	showAllOption: true,
	values: options.customerTypes|default(null),
}) }}
```

Hmm, now I'm thinking it would be an improvement to prefix the category ID with a string (e.g. `"category-" ~ category.id`) and use that as the checkboxes' values instead of using the category slugs. Then I can remove the prefix to get the category's ID instead of doing a query on the slug to get the ID. I'd still prefer to get the category ID by itself somehow, though!

**Comment by BenParizek** [comment]
@missmatsuko I've looked into this a bit more and understand your question better now. What you are trying to do is not possible in Twig with the merge filter. It's just a limitation of how that function behaves, but it's not possible to dynamically set the keys of the merged array to IDs. You can prefix them like you describe and then swap out the strings you added on the reports side of things to get the ids you need. Alternatively, you could handle the logic as you'd like in PHP but that would require building a full report integration, not just running with the existing Twig Template report option.

Something like this should work to get the settings you need:

``` twig
{% set customerTypesCategories = craft.categories
	.group('shopUserType')
	.all() %}

{% set customerTypesOptions = {
	'*': 'All'
} %}

{% for category in customerTypesCategories %}
	{% set customerTypesOptions = customerTypesOptions|merge({
		('category-'~category.id): category.title
	}) %}
{% endfor %}

{{ forms.checkboxSelectField({
	label: 'Customer Types'|t,
	name: 'customerTypes',
	options: customerTypesOptions,
	showAllOption: true,
	values: settings.customerTypes|default(null),
}) }}
```

And you could get the array to query categories in your reports with something like this:

``` twig
{% set categoryIds = [] %}

{% for categorySetting in settings.customerTypes %}
	{% set categoryId = categorySetting|replace('category-', '') %}
	{% set categoryIds = categoryIds|merge([categoryId]) %}
{% endfor %}

{% set categories = craft.categories.id(categoryIds) %}

{% for category in categories %}
	{{ category }}<br>
{% endfor %}
```
