### ISSUE TITLE
Add an example of creating a dynamic config option to your examples

### ISSUE THREAD

**Issue by johnwbaxter** [barrelstrength/craft-sprout-reports#38]
Your examples are great, but nothing in there shows how to create a dynamic config option.

Something like this would be really useful when starting out:

```
{% set catGroup = craft.categories.group('exampleCategoryGroup') %}
{% set cat = [] %}
{% for cat in catgroup %}
	{% set c = c|merge({(c.id) : (c.title)}) %}
{% endfor %}

{{ forms.selectField({
	label: "Example Dropdown Field (Text)"|t,
	name: "exampleDropdownFieldText",
	options: c,
	value: "three"
}) }}
```

**Comment by BenParizek** [comment]
Thanks @johnwbaxter 

We'll work something like this into the examples.

**Comment by BenParizek** [comment]
I've added a basic example to the Twig Template Report docs here: https://sprout.barrelstrengthdesign.com/docs/reports/custom-twig-template-report.html#results-template
