### ISSUE TITLE
Update craft-sprout-reports-users

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-reports#45]
Need to update to support the latest version of Sprout Reports and Craft 3.1:
https://github.com/barrelstrength/craft-sprout-reports-users

This http://share.barrelstrength.co/2ea58acce478 and other errors.

### Notify

- [x] John Baxter (Discord)

**Comment by pdaleramirez** [comment]
@BenParizek This plugin is now updated to support craft 3.1 and the latest base reports dependency. It is on develop branch
