### ISSUE TITLE
Update craft-sprout-reports-categories

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-reports#46]
Need to update to support the latest version of Sprout Reports and Craft 3.1:
https://github.com/barrelstrength/craft-sprout-reports-categories

### Notify

- [x] John Baxter (Discord)

**Comment by pdaleramirez** [comment]
@BenParizek latest commit on develop branch now supports new base reports lib dependencies.

Tested craft 3.1 version. Tested created 2 different field categories and both run report display correct total entries count column
