### ISSUE TITLE
Add support for Date Ranges

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-reports#48]
Date selection will start with one field: **Date Range**

- This Week
- Last Week
- This Month (March)
- Last Month (February)
- This Quarter (Jan-March 2019)
- Last Quarter (Nov-Dec 2018)
- This Year (2019)
- Last Year (2018)
- Custom Date Range

We will automatically set the date range for all the options except "Custom Date Range". When a user selects "Custom Date Range" the Date Range dropdown will show "Custom Date Range" selected and two new fields will appear:

- Start Date
- End Date

A saved report that uses any of the pre-selected options will always pull that range. So, If I save a report for "This Month" today it will always display the current month whenever I run it. We should probably try to indicate the range somewhere on the Results page. Maybe we want to give the "Start Date" and "End Date" fields special treatment if they a Data Source indicates that it uses those values.

We would use these new Date Fields on Commerce Reports and also on Sprout Forms Entries reports and wherever else we have dates. We'd probably want to make them into Twig Macros that were easy for others to reuse too.

**Comment by andrelopez** [comment]
@BenParizek Ready for release
