### ISSUE TITLE
Register Data Source from module

### ISSUE THREAD

**Issue by carlcs** [barrelstrength/craft-sprout-reports#49]
It’s currently not possible to register a custom Data Source from a module. My `DataSource` constructor is throwing an error because `$pluginHandle` is null here 

https://github.com/barrelstrength/craft-sprout-base-reports/blob/a96ae7123904f9bdac542eb7b7ef70e5bb08686c/src/base/DataSource.php#L54

**Comment by BenParizek** [comment]
Thanks @carlcs. We'll look into it and let you know once it's resolved.

**Comment by BenParizek** [comment]
@carlcs This should be resolved in the latest release. Thanks for reporting.
