### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by lindseydiloreto** [barrelstrength/craft-sprout-reports#56]
The "Sprout Website" link is broken...

<img width="581" alt="Ω 2019-06-04 at 12 47 42 PM" src="https://user-images.githubusercontent.com/5309692/58909077-090d6f00-86c7-11e9-9e7f-b0b753914fc2.png">

**Comment by andrelopez** [comment]
Fixed! thanks @lindseydiloreto

**Comment by lindseydiloreto** [comment]
Cool, no problem! 🙂
