### ISSUE TITLE
No value for `$settings`?

### ISSUE THREAD

**Issue by lindseydiloreto** [barrelstrength/craft-sprout-reports#57]
I'm not entirely certain, but I think the `$settings` value isn't getting properly passed in here...

https://github.com/barrelstrength/craft-sprout-reports/blob/v1/src/datasources/CustomTwigTemplate.php#L70

In my own custom data source, I'm overriding that same method. When I check for the `$settings` value, I'm coming up empty-handed.

```php
/**
 * @inheritdoc
 */
public function getResults(Report $report, array $settings = []): array
{
    \Craft::dd($settings);
}
```

Fortunately, it's still possible to get the settings via the report:

```php
$report->getSettings()
```

Maybe that's even the preferred way of accessing the settings? Indeed, you're even relying on that as a fallback...

https://github.com/barrelstrength/craft-sprout-reports/blob/v1/src/datasources/CustomTwigTemplate.php#L198

Which may explain why it slipped through the cracks.

I'm only about 80% certain though... I apologize in advance if this information is incorrect. 🙂

**Comment by BenParizek** [comment]
Thanks @lindseydiloreto. We'll take a look.

**Comment by BenParizek** [comment]
@lindseydiloreto I believe you're right here. This was an oversight as we updated the API from C2. As this would be a breaking change, we're just going to add a deprecation message to this method for now, and will remove things in v2.0. 

Thanks for reporting.

**Comment by lindseydiloreto** [comment]
Cool, no problem! 🍺
