### ISSUE TITLE
Can't create groups on reports index page?

### ISSUE THREAD

**Issue by lindseydiloreto** [barrelstrength/craft-sprout-reports#58]
I've just updated from Craft 2 to Craft 3, and for the most part everything went smoothly.

Quick question though... How can I show each of my custom data sources as separate headers on the index page? This was very easy to do in Craft 2, but I can't figure out how it could be done in Craft 3.

**Craft 2**

<img width="230" alt="Ω 2019-06-04 at 10 47 50 PM" src="https://user-images.githubusercontent.com/5309692/58933129-22d8a180-871b-11e9-8a2d-45ab9011adc9.png">

**Craft 3**

<img width="236" alt="Ω 2019-06-04 at 10 48 08 PM" src="https://user-images.githubusercontent.com/5309692/58933148-3126bd80-871b-11e9-9c64-5b24ca5c7d6b.png">

**Comment by BenParizek** [comment]
Thanks @lindseydiloreto. Looks like a potential oversight on our end. Added to the list.

**Comment by lindseydiloreto** [comment]
Great, thanks @BenParizek! 👍

**Comment by BenParizek** [comment]
@lindseydiloreto This has been added in the latest release v1.3.0.

**Comment by lindseydiloreto** [comment]
Awesome, thanks @BenParizek! 🍺
