### ISSUE TITLE
Unknown Property: Setting unknown property: barrelstrength\sproutbasereports\records\DataSource::viewContext

### ISSUE THREAD

**Issue by outline4** [barrelstrength/craft-sprout-reports#61]
### Description (screenshots, logs, ...)

When trying to install Sprout Reports on a craft cms 3 site. 
You only have to options to "leave it uninstalled", "remove it" or "troubleshoot"

### Steps to reproduce

1. installation (try)

### Additional info

- Craft version: 3.1.33
- PHP version: 7.3.7
- Database driver & version:  MySQL 10.2.25
- Plugins & versions: 1.2.4.

**Comment by outline4** [comment]
Craft Commerce 2.1.7 is installed

**Comment by andrelopez** [comment]
Hi @outline4 

It looks like you have a missing migration. Did you update Sprout Reports before installing the commerce reports plugin? Could you please share your database with us? 
Please use the following email: support@barrelstrengthdesign.com

**Comment by BenParizek** [comment]
@outline4 This issue will likely be a missing migration or something to do with your larger Craft configuration. As a troubleshooting step, I would recommend deleting the entire `vendor/` folder and `composer.lock` and trying to re-run composer update to ensure you have the latest of all plugins and their dependencies. 

If you'd like us to help troubleshoot further, please update this thread or drop us a note with your db and more info and we'll reopen this.
