### ISSUE TITLE
Number of issues after update to 1.2.7

### ISSUE THREAD

**Issue by billymedia** [barrelstrength/craft-sprout-reports#63]
I updated craft to 3.3.5 and reports to 1.2.7.
As a result, a number of issues have occured.

Firstly, when i try and view my report settings screen, i encounter this error:

`Unable to find the template “_includes/forms” in "__string_template__e60f148565babc889213057d2b16062361217bfbefe30e1f5ffa7472072ff2e8" at line 1.`

When i try and run a report, i get this error:

`Unable to find the template “_includes/forms” in "__string_template__e60f148565babc889213057d2b16062361217bfbefe30e1f5ffa7472072ff2e8" at line 1.`

When i try to create a report using my settings template, it errors by saying it cannot find my settings variable. The variable is called 'reportLimit'.

`Key "reportLimit" for array with keys "resultsTemplate, settingsTemplate" does not exist in "__string_template__9952b6d7a668611195ff2c80bf512051af2fcee598f742fa4e022431a825dff0" at line 51.`

All my reports were working fine till the recent update. As a result the client can no longer run reports.

Also, when i try and create a report, the formatting is broken, ie. it displays the html:
`Results Template
The template to use to display results. Learn more about <a href='https://sprout.barrelstrengthdesign.com/docs/reports/custom-twig-template-report.html#results-template&#039;>Results Templates</a>.`

### Steps to reproduce

1. Update to latest 1.2.7 with craft 3.3.5

### Additional info

- Craft version: 3.3.5
- PHP version: 7.1.26
- Plugins & versions: 1.2.7

**Comment by billymedia** [comment]
To get round the issue, i had to copy the _includes/forms folder into my templates folder, is that now the correct way to do that?

**Comment by BenParizek** [comment]
Thanks @billymedia 

I dug into this and it appears Craft changed the behavior of the `renderString` method we were using for this feature behaves. Copying the Craft `_includes/forms` to the front-end is a good workaround right now, and I've opened a ticket with Craft to try to get this functionality back or figure out what I'm missing. Will update when I learn more.

**Comment by BenParizek** [comment]
@billymedia Craft released a fix for the behavior change they introduced when rendering templates the way we were doing with the Twig Template report and I have just cut an updated release of Sprout Reports (v1.2.8) that updates to that new behavior.

**Comment by jamiematrix** [comment]
Sorry to re-open this, but has error returned? 
I'm on Craft 3.4.25, Sprout Reports 1.5.6, and Commerce Data Source for Sprout Reports 1.0.4.

My 'settings' page has the following:
```
{# Number Setting #}
{{ forms.textField({
    label: "Limit"|t,
    name: "limit",
    size: 10,
    value: 1,
    first: true
}) }}
```

Running the report or attempting to change the report settings (e.g. template path, report name etc) gives the error:
`Variable "forms" does not exist in "__string_template__...`

**Comment by BenParizek** [comment]
@jamiematrix I've moved your question to a separate thread as I'm not sure if it's the same issue here yet. Please follow up over here: https://github.com/barrelstrength/craft-sprout-reports/issues/102
