### ISSUE TITLE
When user exports CSV data, I don't want them to get the html

### ISSUE THREAD

**Issue by johnwbaxter** [barrelstrength/craft-sprout-reports#65]
I love to give my users links in the report output so they can go edit a entry that has come out in the report. But, when they go to download the data as csv, they get that <a> element too.

It would be great if there was some way in the template to detect if the report is being run for csv or html and to choose what to output for each.

**Comment by BenParizek** [comment]
@johnwbaxter You are in luck. You can now check for an `isExport` setting in your Twig Template (or PHP reports) to modify the CSV export to do something differently. For example:

```
{% do craft.sproutReports.addHeaderRow(['Row']) %}

{% do craft.sproutReports.addRow([
    isExport ? 'Not Link' : '<a href="">Link</a>'
]) %}
```

We mention this variable in the docs but I still need to add a better example.  Let me know if that works for what you need.

**Comment by johnwbaxter** [comment]
Awesome!! Thanks Ben, that works a treat!!!
