### ISSUE TITLE
ReportQuery/Report::find() not usable in console requests

### ISSUE THREAD

**Issue by d--j** [barrelstrength/craft-sprout-reports#66]
### Description (screenshots, logs, ...)

In 
https://github.com/barrelstrength/craft-sprout-base-reports/blob/e307774013d5d269fc9e2a967a9729019767ba91/src/elements/db/ReportQuery.php#L79-L82

there is an unguarded call to `Craft::$app->request->getBodyParam`. The method `getBodyParam` is not available when this is a console request.

Whenever a report gets updated a UpdateSearchIndex job for this job gets enqueued. This job uses `ReportQuery`. We use a dedicated queue and thus UpdateSearchIndex jobs get executed in a console request instead of a web request.

Possible fix:
```diff
        if (!$this->viewContext) {
            // The request is available on the Element Index page and used for plugin integrations using Sprout Reports
-            $this->viewContext = Craft::$app->request->getBodyParam('criteria.viewContext');
+            $this->viewContext = Craft::$app->request->isConsoleRequest ? null : Craft::$app->request->getBodyParam('criteria.viewContext');
        }
```

### Steps to reproduce

1. Create a console controller e.g. 
```php
class MyController extends \yii\console\Controller
{
    public function actionReportQuery()
    {
        print_r(\barrelstrength\sproutbasereports\elements\Report::find()->all());
    }
}
```
2. execute this controller `./craft my-controller-name/report-query`
3. You get the following exception:
```
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: craft\console\Request::getBodyParam()'

in .../vendor/yiisoft/yii2/base/Component.php:300

Stack trace:
#0 .../vendor/barrelstrength/sprout-base-reports/src/elements/db/ReportQuery.php(81): yii\base\Component->__call('getBodyParam', Array)
barrelstrength/craft-sprout-base-reports#1 .../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1327): barrelstrength\sproutbasereports\elements\db\ReportQuery->beforePrepare()
#2 .../vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#3 .../vendor/yiisoft/yii2/db/Query.php(146): yii\db\QueryBuilder->build(Object(barrelstrength\sproutbasereports\elements\db\ReportQuery))
#4 .../vendor/yiisoft/yii2/db/Query.php(237): yii\db\Query->createCommand(Object(craft\db\Connection))
#5 .../vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
#6 .../vendor/craftcms/cms/src/elements/db/ElementQuery.php(1487): craft\db\Query->all(NULL)
#7 [...]
```

### Additional info

- Craft version: Craft Pro 3.3.11
- PHP version: 7.2.23
- Database driver & version:  MySQL 5.7.27
- Plugins & versions:
Sprout Reports | 1.2.8

**Comment by rungta** [comment]
Hey @BenParizek :wave:. We’re facing the same issue – failed Search Index jobs when the queue is called from the console.

**Comment by BenParizek** [comment]
@d--j @rungta 👋 

This should be resolved in the latest release. Thanks for reporting.
