### ISSUE TITLE
Reports viewed in a browser wider than 974px do not show a horizontal scroll bar

### ISSUE THREAD

**Issue by ldennison-bsd** [barrelstrength/craft-sprout-reports#67]
Whenever I view a report that has many columns (i.e. not fitting on a single page horizontally), the horizontal scroll bar for the report area only shows up if the browser window width is less than 975px. This happens on Chrome (verified), and perhaps other browsers.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_16qkj)

**Comment by BenParizek** [comment]
@ldennison-bsd I believe this is resolved now in the latest release. Let me know if it persists.
