### ISSUE TITLE
First column of web view is automatically sorted in DataTables

### ISSUE THREAD

**Issue by ldennison-bsd** [barrelstrength/craft-sprout-reports#71]
In the web view of the new DataTables layout, the first column of data is being automatically selected for sorting, as if the user clicked the column header to sort by that first column. But it's happening on initial load. In my opinion, the data should NOT be automatically sorted in any way but rather rendered as the query returns it (in case the custom query has ordering itself). I'd guess this is just a simple DataTables configuration issue that's causing the sorting on the frontend after page load/initialization.

**Comment by BenParizek** [comment]
@ldennison-bsd This has been addressed in v1.3.3. The default behavior will now respect whatever the query results are designed to return and there are new settings in the Report sidebar if you wish to order things by a specific column different than the default:

![image](https://user-images.githubusercontent.com/309735/76690895-36eeef00-661b-11ea-9542-3355c4294d93.png)
