### ISSUE TITLE
Reports not visible in Craft 3.4

### ISSUE THREAD

**Issue by Coalescent** [barrelstrength/craft-sprout-reports#75]
### Description

After upgrading to Craft 3.4, all previously existing reports are no longer listed on the `Reports` page.

I believe this is just a display bug on the Reports page. See this output from the console when viewing that page:

![Screen Shot 2020-01-31 at 1 58 51 PM](https://user-images.githubusercontent.com/6394091/73577580-264f3480-4432-11ea-920e-98cc6f8e1b81.png)

Further, if I try to Customize the view on the Reports page, the modal (where you select columns) will produce an error when trying to save those changes: `TypeError: null is not an object (evaluating 'this.$sortAttributesList.find')` for `getSelectedSortAttribute`.

### Steps to reproduce

1. Upgrade to Craft 3.4.1 and Reports 1.2.1.1
2. Go to the Reports page to view reports (you may have to create some first - we already had 3 existing ones)

### Additional info

- Craft version: 3.4.1
- PHP version: 7.3.8
- Database driver & version:  MySQL 5.7.26

**Comment by BenParizek** [comment]
@Coalescent We should have a release with 3.4 support out this coming week for Sprout Reports and our other plugins.

**Comment by BenParizek** [comment]
@Coalescent We've just released Sprout Reports v1.3.0 that adds Craft 3.4 support and resolves this issue.
