### ISSUE TITLE
Unknown column 'sproutreports_reports.emailColumn'...

### ISSUE THREAD

**Issue by benjaminkohl** [barrelstrength/craft-sprout-reports#80]
### Description (screenshots, logs, ...)

When trying to access the Sprout Reports plugin in the control panel, we get the following yii\db\exception:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sproutreports_reports.emailColumn' in 'field list'
The SQL being executed was: SELECT EXISTS(SELECT `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`siteId`, `elements_sites`.`enabled` AS `enabledForSite`, `elements_sites`.`uri`, `sproutreports_reports`.`dataSourceId`, `sproutreports_reports`.`name`, `sproutreports_reports`.`hasNameFormat`, `sproutreports_reports`.`nameFormat`, `sproutreports_reports`.`handle`, `sproutreports_reports`.`description`, `sproutreports_reports`.`allowHtml`, `sproutreports_reports`.`settings`, `sproutreports_reports`.`groupId`, `sproutreports_reports`.`enabled`, `sproutreports_reports`.`emailColumn`, `sproutreports_datasources`.`viewContext`, `elements`.`draftId`, `drafts`.`sourceId` AS `draftSourceId`, `drafts`.`creatorId` AS `draftCreatorId`, `drafts`.`name` AS `draftName`, `drafts`.`notes` AS `draftNotes`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`
FROM `elements` `elements`
INNER JOIN `sproutreports_reports` `sproutreports_reports` ON `sproutreports_reports`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `drafts` `drafts` ON `drafts`.`id` = `elements`.`draftId`
WHERE (`elements_sites`.`siteId`='1') AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL) AND (`drafts`.`sourceId` IS NULL) AND (`elements`.`revisionId` IS NULL)
ORDER BY `elements`.`dateCreated` DESC) `subquery`
INNER JOIN `sproutreports_reports` `sproutreports_reports` ON `sproutreports_reports`.`id` = `subquery`.`elementsId`
INNER JOIN `sproutreports_datasources` `sproutreports_datasources` ON `sproutreports_datasources`.`id` = `sproutreports_reports`.`dataSourceId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `drafts` `drafts` ON `drafts`.`id` = `elements`.`draftId`
ORDER BY `elements`.`dateCreated` DESC)

I did some digging in the source and I found a migration that was supposed to add that column but it isn't even in the plugin repository. It is in the sprout-base-reports repo. What confuses me about this is that I ran `composer update` without changing a thing in composer.json and all three of the other sprout-base repos got updated which seems like a weird way to push updates to a plugin without actually updating the plugin.

```
- Updating barrelstrength/sprout-base (5.1.1 => 5.1.2): Downloading (100%)         
- Updating barrelstrength/sprout-base-fields (1.3.1 => 1.3.2): Downloading (100%)         
- Updating barrelstrength/sprout-base-reports (1.4.1 => 1.4.2): Downloading (100%)    
```

I know plugins almost always have various dependencies and many don't specify exact versions of the dependencies but it seems unusual that "native" pieces of the plugin itself are broken out into other independently updated repositories. I've seen this done with one other plugin and it usually leads to problems. It seems like it would be a support nightmare because then people using the same version of the plugin could technically run into different issues due to different versions of the underlying packages that make up the entirety of the plugin.

We always specify versions of plugins in composer.json so that updating of plugins can only be done intentionally and never as a side effect of trying to update something else.

Anyway, I've tried manually running migrations and the Yii migration tool behaves as if there is nothing to migrate. So our client is unable to access their reports until we figure out a way to get the plugin _truly_ up-to-date. I'd rather not manually add that column because that migration is still lingering out there and is not logged in the Craft migrations table.

```
php craft migrate/up --plugin=sprout-reports
```

### Steps to reproduce

1. Update to Sprout Reports 1.2.11
2. Try to access it in the control panel.

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.3.9
- Database driver & version:  MySQL 5.7.26
- Plugins & versions:

Sprout Reports 1.2.11

**Comment by BenParizek** [comment]
@benjaminkohl We're working on a fix.

You're correct about the placement of the migration in a shared module and that it can be tricky at times. We also found it tricky to duplicate code that does the same thing in multiple plugins. Both scenarios lead to similar challenges in managing code in multiple places. For better or worse, this is where we have landed right now. It has taken a few rounds to get to a consistent workflow for supporting the core Email and Reports functionality across multiple plugins but composer helps define what dependencies are required for the version of a plugin someone has installed. 

In any case, your feedback is welcome and we'll keep considering how to make this a better process.

**Comment by BenParizek** [comment]
@benjaminkohl After digging into this a bit more I see your comments more clearly now.

Is there a reason you need to be on Sprout Reports v1.2.11 and can't update to the latest? The issue, in your case, is what you described in that v1.2.11 is pulling in the most recent version of Sprout Base Reports which is assuming a different data structure. The schemaVersion in the Sprout Reports plugin only gets bumped up to trigger the necessary migration in Sprout Reports v1.3.0.

I'll consider how we can better solve this with our own composer version dependencies moving forward, but right now I think we'll need to get you updated to the latest Sprout Reports (>v1.3.0) to get that migration triggered.

**Comment by benjaminkohl** [comment]
This is exactly what I thought the issue was. According to the Craft control panel updates page, we are on the latest version of Sprout Reports that is supported by Craft 3.3 and we do not intend to update this particular site to Craft 3.4 and are instead waiting for 3.5.

Is it possible that you can tell me which versions of those underlying base packages are compatible with Sprout Reports 1.2.11? If so, I can just add those versions to our own composer.json file and run the update.

**Comment by BenParizek** [comment]
@benjaminkohl Yeah, I'm looking into that now to get it documented for folks. This is likely going to affect Sprout Email and Sprout Forms as well for folks who don't want to update to Craft 3.4 yet. The bug here is that we didn't bump the dependency versions to a new major version with the 3.4 compatible releases.

For Sprout Reports, these are the dependencies that come right before the ones that add 3.4 support. To stay compatible with Craft 3.3 I believe you will want to target the specific dependencies below:

```
"barrelstrength/sprout-reports": "1.2.11",
"barrelstrength/sprout-base": "5.0.9",
"barrelstrength/sprout-base-reports": "1.3.10"
```
Whenever you are ready to add 3.4 support, you can drop the `sprout-base` and `sprout-base-reports` dependencies and let Sprout Reports pull in whatever it has required again.

**Comment by benjaminkohl** [comment]
The plugin is now back in working order. Thank you for the timely responses and solution to the issue. I'll be sure to leave myself a note about removing those dependencies from our project composer.json when we do go to update eventually.
