### ISSUE TITLE
Name already taken

### ISSUE THREAD

**Issue by johnj24** [barrelstrength/craft-sprout-reports#90]
### Description (screenshots, logs, ...)
I accidentally created a report when it should have been a mailing list. I deleted the report and went to create the mailing list with the same name, except its telling me the name is already taken despite it being deleted prior to this.

### Steps to reproduce

1. Create report with name "Vendors"
2. Delete report named "Vendors"
3. Create mailing list (Data Source: Users)
4. Name it "Vendors"
5. Hit Save

### Additional info

- Craft version: 3.4.17.1
- PHP version: 7.0.33
- Database driver & version:  MySQL 5.7.24
- Plugins & versions: Sprout Reports 1.5.3

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
Thanks @johnj24, I can reproduce.

I believe this is a bug in the Delete Element Action. It appears deleting a report from the Edit page deletes it completely where deleting it from the Element Index via the Element Action only soft deletes it.

If you need a short-term workaround before we have a fix out, you can find the "Vendors" report in the `sproutreports_reports` table and change the name and handle of the deleted record and that should let you create a new Report by the same name again.

We'll work on getting a fix in place and I'll update this thread when I do.

**Comment by BenParizek** [comment]
@johnj24 This is resolved in Sprout Reports v1.5.4
